/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/BookNewRide`; params?: Router.UnknownInputParams; } | { pathname: `/CreateAccount`; params?: Router.UnknownInputParams; } | { pathname: `/Drivers`; params?: Router.UnknownInputParams; } | { pathname: `/ForgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `/Home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/RideHistory`; params?: Router.UnknownInputParams; } | { pathname: `/SendCode`; params?: Router.UnknownInputParams; } | { pathname: `/Signin`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/BookNewRide`; params?: Router.UnknownOutputParams; } | { pathname: `/CreateAccount`; params?: Router.UnknownOutputParams; } | { pathname: `/Drivers`; params?: Router.UnknownOutputParams; } | { pathname: `/ForgotPassword`; params?: Router.UnknownOutputParams; } | { pathname: `/Home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `/RideHistory`; params?: Router.UnknownOutputParams; } | { pathname: `/SendCode`; params?: Router.UnknownOutputParams; } | { pathname: `/Signin`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/BookNewRide${`?${string}` | `#${string}` | ''}` | `/CreateAccount${`?${string}` | `#${string}` | ''}` | `/Drivers${`?${string}` | `#${string}` | ''}` | `/ForgotPassword${`?${string}` | `#${string}` | ''}` | `/Home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/Profile${`?${string}` | `#${string}` | ''}` | `/RideHistory${`?${string}` | `#${string}` | ''}` | `/SendCode${`?${string}` | `#${string}` | ''}` | `/Signin${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/BookNewRide`; params?: Router.UnknownInputParams; } | { pathname: `/CreateAccount`; params?: Router.UnknownInputParams; } | { pathname: `/Drivers`; params?: Router.UnknownInputParams; } | { pathname: `/ForgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `/Home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/RideHistory`; params?: Router.UnknownInputParams; } | { pathname: `/SendCode`; params?: Router.UnknownInputParams; } | { pathname: `/Signin`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
